export const BASE_URL = ""
export const PRODUCT_URL = "/api/products"
export const USER_URL = "/api/users"
export const ORDER_URL = "/api/orders"
export const PAYPAL_URL = "/api/config/paypal"
export const UPLOAD_URL = "/api/upload"